image:
  file: .gitpod.Dockerfile

# exposed ports
ports:
- port: 5432 # PostgreSQL
  onOpen: ignore
- port: 8080 # Web
  onOpen: open-preview
- port: 8443 # SSL
  onOpen: ignore

# Start up tasks:
tasks:
  # Will be executed one time when creating a workspace, command: will be excuted each time you open workspace
  - init: |
      sudo sed 's/peer/md5/g' /etc/postgresql/12/main/pg_hba.conf
      pg_ctl reload
      sleep 1
      psql -U gitpod -c "CREATE ROLE postgres SUPERUSER LOGIN PASSWORD 'postgres'"
      psql -U gitpod -c "CREATE ROLE helicaldb SUPERUSER LOGIN PASSWORD 'helicaldb'"
      pg_ctl restart
    command: |
      sleep 1
  - command: gp await-port 8080 && sleep 3 && gp preview "$(gp url 8080)"
